shared: fix onEvent typings & add getByScriptID to client Entity
altmp/altv-js-module-v2 pull request #130
Opened 2023-10-11 02:36 UTC by Yiin

2023-10-11 10:07 UTC, xLuxy requested changes

2023-10-11 10:07 UTC, xLuxy commented on client/src/helpers/NativeInvoker.h
> +                pointersCount = 0;
don't do that

2023-10-11 10:07 UTC, xLuxy commented on client/src/helpers/NativeInvoker.h
> +                pointersCount = 0;
don't do that

2023-10-11 10:07 UTC, xLuxy commented on client/src/helpers/NativeInvoker.h
> +                free(stringValues[nextString]);
You free memory here, but when will you free the actual memory once invocations is done?

2023-10-11 10:30 UTC, LeonMrBonnie commented
Just remove all the changes to natives, I will fix that myself

2023-10-14 09:49 UTC, Yiin commented
@LeonMrBonnie done

2023-10-16 16:52 UTC, LeonMrBonnie commented
i forgor

2023-10-16 16:52 UTC, merged