Added server events
altmp/altv-js-module-v2 pull request #14
Opened 2023-04-29 21:31 UTC by Davidos-HDT

2023-04-29 21:33 UTC, Davidos-HDT commented on types/server/index.d.ts
> +            readonly state: boolean;
It's correct type, for this param?

2023-04-29 21:39 UTC, Davidos-HDT commented on types/server/index.d.ts
> +        export const onServerStarted: Event<EventContext>;
This event dont have params. And i don't know how can write, its correct?

2023-04-30 14:24 UTC, LeonMrBonnie requested changes
Thanks for your contribution

2023-04-30 14:24 UTC, LeonMrBonnie commented on server/js/events/player.js
> -Event.register(alt.Enums.EventType.PLAYER_REQUEST_CONTROL, "PlayerControlRequest");
Per the [event naming conventions](https://github.com/altmp/altv-js-module-v2/blob/master/docs/adding-events.md#event-naming) the verb should be at the end, so the previous name was correct

2023-04-30 14:24 UTC, LeonMrBonnie commented on types/server/index.d.ts
> +        export interface EventContext {
The `EventContext` and `Event` interfaces should be imported and used from shared, instead of duplicating them here

2023-04-30 14:24 UTC, LeonMrBonnie commented on types/server/index.d.ts
> +            readonly state: boolean;
Yes.

2023-04-30 14:24 UTC, LeonMrBonnie commented on types/server/index.d.ts
> +        export const onServerStarted: Event<EventContext>;
It is fine like that.

2023-04-30 14:24 UTC, LeonMrBonnie commented on types/server/index.d.ts
> +    export interface IConnectionInfo {
Neither `IConnectionInfo` nor `IConnectionQueueInfo` exists in the code, as the connection queue is not implemented yet

2023-04-30 14:24 UTC, LeonMrBonnie commented on types/shared/index.d.ts
> +        export const enum ExplosionType {
The naming of the enum values should be consistent with other enums

2023-04-30 14:24 UTC, LeonMrBonnie commented on types/shared/index.d.ts
> +        export const enum ExplosionType {
The same thing applies to the BodyPart enum

2023-04-30 14:24 UTC, LeonMrBonnie commented on types/shared/index.d.ts
> +        export const enum ConnectDeniedReason {
This enum doesn't exist anywhere, only enums that are actually also exposed by the [Enums namespace](https://github.com/altmp/altv-js-module-v2/blob/master/shared/src/namespaces/EnumsNamespace.cpp#L32) should be added here.

2023-04-30 15:08 UTC, Davidos-HDT commented on types/server/index.d.ts
> +        export interface EventContext {
I should write like this?
```
interface PlayerConnectEventContext extends shared.Events.EventContext {
    readonly player: Player;
}

export const onPlayerConnect: shared.Events.Event<PlayerConnectEventContext>;
```

2023-04-30 19:37 UTC, Davidos-HDT commented on types/shared/index.d.ts
> +        export const enum BodyPart {
This enum doesn’t exist on this [list](https://github.com/altmp/altv-js-module-v2/blob/ce3aafd54aa2ae6d5ec22b3a129c8af36ffe3712/shared/src/namespaces/EnumsNamespace.cpp#L32), but you didn’t say anything about that enum, and I left it.

2023-04-30 19:40 UTC, Davidos-HDT commented on types/shared/index.d.ts
> +        static fromArray(array: Array<number>): Quaternion;
matrix, array param have `Array<number>` type or `ReadonlyArray<number>`?

2023-04-30 20:55 UTC, LeonMrBonnie commented on types/shared/index.d.ts
> +        static fromArray(array: Array<number>): Quaternion;
`ReadOnlyArray` is only useful for return values

2023-04-30 20:57 UTC, LeonMrBonnie commented on types/shared/index.d.ts
> +        export const enum BodyPart {
I actually forgot to add that one, I will add it, so yes this enum can stay in the types

2023-04-30 21:04 UTC, LeonMrBonnie commented on types/server/index.d.ts
> +        export interface EventContext {
yes

2023-04-30 21:04 UTC, LeonMrBonnie approved these changes
Thanks

2023-04-30 21:05 UTC, merged