shared: remove `is` prefix from JavaScript class properties
altmp/altv-js-module-v2 pull request #192
Opened 2024-02-21 20:59 UTC by carlos-menezes

Closes #182

2024-02-25 15:28 UTC, xLuxy commented
Hey, have you checked v1 typings and `*/js/compatiblity` stuff? You might break v1 compat with the changes you made.

2024-02-25 15:36 UTC, xLuxy reviewed
Please go through all v1 bindings (source code, not typings) and fix compatiblity classes. For example, with your change, you're breaking `alt.isClient` / `alt.isServer` - and there are more.

2024-03-02 17:44 UTC, Yiin commented
@carlos-menezes remove "Draft" tag once it's ready for review 👍

2024-03-08 17:27 UTC, carlos-menezes commented
Sorry for the delay, @Yiin . Will look into the rest of this PR this weekend.

2024-03-19 07:07 UTC, xLuxy commented
Hey there, any progress on this?

2024-03-19 09:41 UTC, carlos-menezes commented
Really sorry for the delay, these last few weeks have been crazy. Anyway, I'm marking this a ready for review after the last commit. Let me know about any wrong-doings.

2024-03-19 10:08 UTC, xLuxy requested changes
We should keep methods prefixed with `is` since they're more fitting in most cases.

Also, please make sure typings are updated accordingly aswell as **all** binding files are updated to reflect changes - your changes potentially break things there.

2024-03-19 10:08 UTC, xLuxy commented on client/js/compatibility/classes/webview.js
> -    get isVisible() {
This aswell as the setter have to stay - see https://github.com/altmp/altv-types/blob/dev/client/index.d.ts#L3328

2024-03-19 10:08 UTC, xLuxy commented on client/src/classes/RmlElement.cpp
> +    tpl.Method<&alt::IRmlElement::IsPointWithinElement>("pointWithinElement");
Maybe should still be prefixed with `is` here because it's a method and is more fitting?

2024-03-19 10:08 UTC, xLuxy commented on server/src/classes/VoiceChannel.cpp
> +    tpl.Method<&alt::IVoiceChannel::IsPlayerMuted>("playerMuted");
Maybe should still be prefixed with is here because it's a method and is more fitting?

2024-03-19 10:45 UTC, closed without merging