server: v1-compatible Vehicle class
altmp/altv-js-module-v2 pull request #83
Opened 2023-09-19 20:56 UTC by Yiin

2023-09-19 23:12 UTC, xLuxy requested changes

2023-09-19 23:12 UTC, xLuxy commented on server/src/classes/Vehicle.cpp
> +    tpl.Method<&alt::IVehicle::GetPartBulletHoles>("getPartBulletHoles");
This is already present in `SharedVehicle.cpp` on Line ~102

2023-09-19 23:12 UTC, xLuxy commented on shared/src/classes/SharedVehicle.cpp
> +    tpl.Method<&alt::IVehicle::DoesWheelHasTire>("doesWheelHasTire");
This also exists in `SharedVehicle.cpp` on line ~100

2023-09-19 23:13 UTC, Yiin commented on shared/src/classes/SharedVehicle.cpp
> +    tpl.Method<&alt::IVehicle::DoesWheelHasTire>("doesWheelHasTire");
this is shared file lol

2023-09-21 07:43 UTC, nrzull commented on client/js/compatibility/classes/vehicle.js
> +        return super.isManulEngineControl;
super.isManu**a**lEngineControl

2023-10-01 18:27 UTC, notmatical commented
so test it 😮‍💨

2023-10-02 01:45 UTC, Yiin commented
> so test it 😮‍💨

it's open source, no one is stopping you.

2023-10-03 10:57 UTC, LeonMrBonnie commented
Most of the API changes here are wrong, the prefix `is` for properties is only allowed to be used when it is read-only.

2023-10-07 14:32 UTC, closed without merging